### ISSUE TITLE
weird residual doc pages

### ISSUE THREAD

**Issue by petigura** [California-Planet-Search/radvel#108]
Hey, @bjfultn.

Sean and I noticed that there are some out of date doc pages 

http://radvel.readthedocs.io/en/master/quickstart.html

I think these have been superseded. IS RTD still compiling docs from master?

**Comment by bjfultn** [comment]
I believe the stale master branch build is cleared out now. I had to push "clean" on the list of versions on readthedocs.org. Master was the only inactive version that showed this option. I think because it was the only one that was being built in the past but no longer. The other branch versions (e.g. even-dev) were never built in the first place so their pages do not exist.
