### ISSUE TITLE
Celerite Problems During Installation

### ISSUE THREAD

**Issue by smmills** [California-Planet-Search/radvel#162]
If I 
```
$pip install radvel --user 
```
on cadence, it installs radvel and dependencies without reporting problems, however I can not load radvel in python. I get:
```
>>> import radvel
WARNING: KEPLER: Unable to import C-based Kepler'sequation solver. Falling back to the slower NumPy implementation.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "radvel/__init__.py", line 1, in <module>
    from .model import *
  File "radvel/model.py", line 7, in <module>
    from radvel import gp
  File "radvel/gp.py", line 7, in <module>
    import celerite
ImportError: No module named celerite
```
If I then manually pip install celerite, this problem goes away.
If this package is required to load radvel, why is it not a required dependency?

**Comment by bjfultn** [comment]
celerite requires building and is a few percent more difficult to install than the rest of the dependencies because of this. It is also only needed in special cases when using the celerite kernel with GPs. I've now made it optional in the sense that radvel will work without it and throw a warning message. I've also added a note about this in the install documentation.
