### ISSUE TITLE
Omega affects RVs when ecc = 0

### ISSUE THREAD

**Issue by andrewwaynemayo** [California-Planet-Search/radvel#167]
In `kepler.py`, the radial velocities depend on the variable `om` even when eccentricity `e == 0`. But if `e == 0` doesn't that mean that `om` should have no effect on the output?

If this is an issue I believe it could be fixed by changing line 37 from `return k * np.cos(m + om)` to `return k * np.sin(m)`.

There may be something similar in the non-eccentric case (i.e. a cosine may need to be changed to a sine to ensure RV = 0 at time of conjunction) but I haven't checked that case so I'm not sure.

**Comment by sealauren** [comment]
Hi Andy!  Note that the calculation of m depends on tp (which is also formally undefined when e==0).  If you are initiating your model in a basis that uses tc instead of tp, the time of conjunction is converted to a time of periastron passage (utilizing omega) that is then passed to kepler.py, so the choice of omega should not matter in the e==0 case.  I recommend reading orbit.py and basis.py to get a sense of what's going on under the hood.  Also, Fulton et al. (2018) provides substantial documentation of the orbit model. http://adsabs.harvard.edu/abs/2018arXiv180101947F

In general, the RV does not need to be zero at the time of conjunction.

**Comment by andrewwaynemayo** [comment]
Hi Lauren! I see what you mean now. Thanks for the clarification!
