### ISSUE TITLE
Length of flatchains DataFrame

### ISSUE THREAD

**Issue by lhirsch238** [California-Planet-Search/radvel#196]
The length of the DataFrame containing the flatchains is not equivalent to nwalkers x nsteps x nensembles. When I run with
 --nwalkers=52 --nsteps=200 -- nensembles=24
 I get a DataFrame with length 187200 (= 52 x 200 x 16). 

Running with 
--nwalkers=52 --nsteps=200 --nensembles=16 
 I get length 124800 (= 52 x 200 x 12).

I'm not sure where the final dimension is coming from, but it seems like 8 less than the number of ensembles.

**Comment by bjfultn** [comment]
The length of the DataFrame should be:
`nwalkers*nensmbles*steps_taken`
`steps_taken` is not necessarily equal to `nsteps` because convergence can happen early, but `steps_taken` will always be `<=nsteps`
In this case it looks like it ended up saving (after burn in) 150 steps per walker. I believe at least 5% of the steps must be thrown out in burn-in, but those steps can't get thrown out before 50 steps are evaluated because thats the G-R/Tz status checking interval.
