### ISSUE TITLE
Rounding error on HardBounds prior

### ISSUE THREAD

**Issue by lhirsch238** [California-Planet-Search/radvel#205]
After performing a least squares fit using a HardBounds prior on jitter, the jitter parameter value went to 20.000000000004569, over the 20 m/s allowable value of the prior most likely due to a rounding error. This causes the prior to return -inf, which in turn drives the logprob value to -inf. The code is then unable to recover on subsequent fits with model parameters changed.

**Comment by bjfultn** [comment]
I think the issue here is as @leerosenthalj suggested. Sometimes the minimizer takes a step over this boundary and then can't ever get back because the likelihood is -np.inf. 

I think the solution is to penalize solutions exponentially as they approach the hard boundaries, or use a different minimizer that can accept boundaries and then feed our hard bounds into that.

**Comment by bjfultn** [comment]
There was a bug in @leerosenthalj's code that was preventing priors from being applied as intended. 

I think that the issue here is now truly, simply related to rounding errors near the boundaries.

**Comment by bjfultn** [comment]
If this is really a rounding issue, I believe it can be fixed by changing to inclusive boundaries. So I changed
`if x < self.minval or x > self.maxval:`
to 
`if x <= self.minval or x >= self.maxval:`

This will be employed in v1.2.7. @lhirsch238 feel free to re-open or re-report this issue if it still pops up after this fix.
