### ISSUE TITLE
Example ipython notebooks -> static documentation

### ISSUE THREAD

**Issue by petigura** [California-Planet-Search/radvel#23]
The ipython notebooks are carrying around the inline images which is causing the github repo to be pretty bloated.  Let's follow this example more closely.

http://dan.iel.fm/george/current/user/quickstart/#a-simple-example

**Comment by howardisaacson** [comment]
Hi Erik,

I assume you are talking about: flatchain. Looks valuable for plotting subsets of mcmc chains.

Howard

**Comment by petigura** [comment]
Yes, but we don't need to carry it around in the git repo. The biggest files are in the tests directory. Every time we rerun the tests and commit, we store a new copy of the output plots. This will quickly cause the repo to become bloated.

[radvel]$ du -h
8.0K	./bin
 80K	./example_data
 12K	./example_planets
120K	./radvel/data
8.0K	./radvel/planets
3.4M	./radvel/tests/.ipynb_checkpoints
4.8M	./radvel/tests
5.2M	./radvel
 28K	./rvlin
736K	./src
532K	./tests/.ipynb_checkpoints
4.7M	./tests
 35M	.

**Comment by bjfultn** [comment]
I converted the K2-24 tutorial into a static document that is now available on readthedocs (http://radvel.readthedocs.io/en/cli/tutorials.html). I think we should keep the notebook in the repo but not with the images embedded. We can use the ``radvel`` command line interface and the K2-24 and HD164922 example configuration files as our unit tests now instead of these iPython notebooks so those shouldn't ever really change.

I'll work on the HD164922 example next, and probably trim it down a lot since it is mostly duplicated in the K2-24 example. The only major difference is the multiple telescopes.

**Comment by petigura** [comment]
great stuff, @bjfultn. One trick for simplify the building of the docs is to put the code examples in to a .py file and then, include the lines with the `literalinclude` command in rst. For example, the plots for the `specmatch-emp` quickstart are run by calling

https://github.com/samuelyeewl/specmatch-emp/blob/master/docs/quickstart.py

which generates the figures which are typeset here:

https://github.com/samuelyeewl/specmatch-emp/blob/master/docs/quickstart.rst

This way, no duplication of code is necessary.

**Comment by bjfultn** [comment]
@petigura Do you know how I could include code directly from the iPython notebook? If I put the code in a `.py` file then I'll still have two copies. One in the `.py` and one in the iPython notebook.

**Comment by petigura** [comment]
Thanks for creating the static docs for k2-24. Closing the issue!
