### ISSUE TITLE
lnprob NaN with MCMC

### ISSUE THREAD

**Issue by SpaceyCaseyLynn** [California-Planet-Search/radvel#266]
Hi, I have the attached config file, and I keep getting the error lnprob returned NaN when I try to run radvel mcmc -s file. I've tried troubleshooting for a while (+ with my advisor Lauren Weiss) and we can't figure out why. If someone can help out I'd be very grateful. 
[k102.py.zip](https://github.com/California-Planet-Search/radvel/files/3752972/k102.py.zip)
<img width="921" alt="Screen Shot 2019-10-21 at 11 15 23 AM" src="https://user-images.githubusercontent.com/56848786/67244560-aa3a5f00-f3f5-11e9-9753-7fe3c811faf1.png">

**Comment by bjfultn** [comment]
The problem here is that the `logk` parameters are running away to -infinity and essentially causing a floating point overflow. This can happen when working in the `logk` basis with poor constraints on k. The prior overwhelms the data and drives the fit to K=0. Try imposing priors on one or both of the `logk` parameters or fit using the `per tc secosw sesinw k` basis.

**Comment by sealauren** [comment]
Thanks BJ!
